### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by leesoojeong**
## What does this PR do?

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code Style Update (formatting, renaming)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Other (please describe):

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ssm0318** [comment]
요거 필요한건가요? 이미 main에 머지하신거죠?

**Comment by leesoojeong** [comment]
approve가 필요해서 아직 머지 못했습니다.

**Comment by ssm0318** [comment]
앗 그 branch 권한설정 바꿔서 force push 한줄 얼른 할게여 죄송함다

**Review by ssm0318 — APPROVED** [review]

**Comment by ssm0318** [comment]
여기에 제가 방금 develop에 머지시킨 내용 (issue #60)도 포함돼서 머지되나요...? 그건 아닌가
그건 시급하게 머지해야될 것 같기는 해가지구

**Comment by leesoojeong** [comment]
@ssm0318 기본적으로 squash and merge로 issue #60을 머지시키는게 맞지만 이미 create a merge commit으로 머지를 진행해버려서 이번 경우에만 그대로 진행하겠습니다. 다음부터는 squash and merge로 머지해주세요! (develop -> main 제외: 이 경우는 rebase and merge입니다.)

**Pull request merged**
